### Codio Activity 22.2: Multiple Nodes

**Expected Time = 60 minutes**

**Total Points = 60**

This activity focuses on expanding the neural network to use three nodes for a prediction.  The main difference from your prior activity is that for each new node you will need a corresponding set of weights for features and bias.  Again, you will use a small sample of the titanic dataset to test the networks forward pass.

#### Index

- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)
- [Problem 4](#-Problem-4)
- [Problem 5](#-Problem-5)
- [Problem 6](#-Problem-6)

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
import seaborn as sns
titanic = sns.load_dataset('titanic').dropna(subset = ['age'])
X = titanic[['age', 'fare']].head()
y = titanic['survived'].head()

[Back to top](#-Index)

### Problem 1

#### Add bias

**10 Points**

Again, you will need to add a bias term to the data.  Complete the function below to add a column of 1's as the first column of your data.

In [17]:
### GRADED
def add_bias(X):
    '''
    This function adds a bias feature
    as the lead column to an array X.
    '''
    return ''
    
### BEGIN SOLUTION
def add_bias(X):
    bias = pd.Series(np.ones(len(X)), name = 'bias')
    ans = pd.concat([bias, X], axis = 1)
    return ans
### END SOLUTION

### ANSWER CHECK
X_with_bias = add_bias(X)
X_with_bias.head()

bias   age     fare
0   1.0  22.0   7.2500
1   1.0  38.0  71.2833
2   1.0  26.0   7.9250
3   1.0  35.0  53.1000
4   1.0  35.0   8.0500

In [18]:
### BEGIN HIDDEN TESTS
def add_bias_(X):
    bias = pd.Series(np.ones(len(X)), name = 'bias')
    ans = pd.concat([bias, X], axis = 1)
    return ans
X_with_bias_ = add_bias_(X)
#
#
#
np.testing.assert_array_equal(X_with_bias, X_with_bias_)
### END HIDDEN TESTS

[Back to top](#-Index)

### Problem 2

#### A weight array

**10 Points**

Now, because you are working with three layers, you need to create weights for the bias and each feature in each node.  This means for a 3-node layer you will need three rows of three columns of weights.  Create this array below as `weights` using `np.random.normal` with `np.random.seed(42)`. 

In [19]:
### GRADED
weights = ''
    
### BEGIN SOLUTION
np.random.seed(42)
weights = np.random.normal(size = (3, 3))
### END SOLUTION

### ANSWER CHECK
print(weights.shape)
print(weights)

(3, 3)
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]


In [20]:
### BEGIN HIDDEN TESTS
np.random.seed(42)
weights_ = np.random.normal(size = (3, 3))

#
#
#
np.testing.assert_array_equal(weights, weights_)
### END HIDDEN TESTS

[Back to top](#-Index)

### Problem 3

#### Weighted Sum

**10 Points**


Again, you will use the weights to compute a weighted sum of the features and bias term with the weights.  The result should be a `(5, 3)` array.  Assign this as `layer_1_output` below.

In [21]:
### GRADED
layer_1_output = ''
    
### BEGIN SOLUTION
layer_1_output = X_with_bias@weights
### END SOLUTION

### ANSWER CHECK
print(layer_1_output)

            0          1          2
0   45.452664   0.274263  -7.907014
1  170.943350  45.669187 -41.715199
2   52.610752  -0.144332  -9.160457
3  137.658960  32.417152 -32.476195
4   66.515422  -2.155783 -11.326374


In [22]:
### BEGIN HIDDEN TESTS
layer_1_output_ = X_with_bias_@weights_

#
#
#
np.testing.assert_array_equal(layer_1_output, layer_1_output_)
### END HIDDEN TESTS

[Back to top](#-Index)

### Problem 4

#### Activation

**10 Points**


Again, use a sigmoid activation function to transform the results of the weighted sum using the sigmoid function to apply the activation function.  Assign the results as a DataFrame to `layer_1_activation` below.

In [27]:
### GRADED
def sigmoid(x):
    return ''

layer_1_activation = ''
    
### BEGIN SOLUTION
def sigmoid(x):
    return 1/(1 + np.exp(-x))
layer_1_output = X_with_bias@weights
layer_1_activation = sigmoid(layer_1_output)
### END SOLUTION

### ANSWER CHECK
print(type(layer_1_activation))

<class 'pandas.core.frame.DataFrame'>


In [28]:
### BEGIN HIDDEN TESTS
def sigmoid_(x):
    return 1/(1 + np.exp(-x))
layer_1_output_ = X_with_bias_@weights_
layer_1_activation_ = sigmoid_(layer_1_output_)

#
#
#
pd.testing.assert_frame_equal(layer_1_activation, layer_1_activation_)
### END HIDDEN TESTS

[Back to top](#-Index)

### Problem 5

#### Bias Term

**10 Points**


The array from above will need to again have weights applied, and these include a weight for a bias term.  Use your function to again add a bias term and assign the resulting array to `layer_1_with_bias` below.  Then create an appropriately sized array of weights for a single node named `weights_2` again using `np.random.seed(42)`.  

In [29]:
### GRADED
layer_1_with_bias = ''
weights_2 = ''
    
### BEGIN SOLUTION
layer_1_with_bias = add_bias(layer_1_activation)
np.random.seed(42)
weights_2 = np.random.normal(size = (4,))
### END SOLUTION

### ANSWER CHECK
print(layer_1_with_bias)
print(weights_2)

   bias    0         1             2
0   1.0  1.0  0.568139  3.680168e-04
1   1.0  1.0  1.000000  7.643973e-19
2   1.0  1.0  0.463980  1.051038e-04
3   1.0  1.0  1.000000  7.866251e-15
4   1.0  1.0  0.103792  1.205072e-05
[ 0.49671415 -0.1382643   0.64768854  1.52302986]


In [30]:
### BEGIN HIDDEN TESTS
layer_1_with_bias_ = add_bias(layer_1_activation_)
np.random.seed(42)
weights_2_ = np.random.normal(size = (4,))

#
#
#
np.testing.assert_array_equal(weights_2, weights_2_)
### END HIDDEN TESTS

[Back to top](#-Index)

### Problem 6

#### Output of First Pass

**10 Points**


Finally, use the weights and bias added data from the first layer to compute the weighted sum and pass the results through a sigmoid activation.  Use these results to predict the positive class if output > 0.5 and class 0 otherwise.  What is the accuracy on the dataset -- assign to `acc_first_pass` below.

In [31]:
### GRADED
ans = ''
acc_first_pass = ''
    
### BEGIN SOLUTION
ans = layer_1_with_bias  @ weights_2
acc_first_pass = sum(y == np.where(sigmoid(ans) > .5, 1, 0))/len(y)
### END SOLUTION

### ANSWER CHECK
print(acc_first_pass)

0.6


In [32]:
### BEGIN HIDDEN TESTS
ans_ = layer_1_with_bias_  @ weights_2_
acc_first_pass_ = sum(y == np.where(sigmoid(ans_) > .5, 1, 0))/len(y)


#
#
#
np.testing.assert_array_equal(ans, ans_)
assert acc_first_pass_ == acc_first_pass
### END HIDDEN TESTS

Great job!  Obviously we hope to use a better approach than purely random weights -- this is where backpropogation comes in.  Next you will iteratively update these weights to hopefully improve the performance of the network.