### Codio Activity 22.1: A Simple Network

**Expected Time = 60 minutes** 

**Total Points = 50**

This activity focuses on the basics of an artificial neural network (ANNs).  Using the titanic dataset you will work through the basic steps of the neural network's forward pass.  This means adding a bias feature, creating weights, applying the weights and activation function, and making predictions using the results of a sigmoid activation. 

#### Index

- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)
- [Problem 4](#-Problem-4)
- [Problem 5](#-Problem-5)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Creating the Data

Below, we load in the titanic dataset from `seaborn`.  Note that this dataset has missing values in the `age` column that are subsequently dropped.  This exercise only uses the top five rows as that dataset in order to clarify the initial workings of ANNs



In [5]:
import seaborn as sns

In [7]:
titanic = sns.load_dataset('titanic').dropna(subset = ['age'])

In [9]:
X = titanic[['age', 'fare']].head()
y = titanic['survived'].head()

### Problem 1

#### Adding the Bias Feature

**10 Points**

Complete the function `add_bias` below to add a column of ones which will act as the bias feature for the data `X`. 

As a convention, add the bias column as the first column in the dataset. 

In [11]:
### GRADED
def add_bias(X):
    '''
    bias = ''
    ans = ''
    
    This function adds a bias feature
    as the lead column to an array X.
    
    HINT: try using pd.series and pd.concat
    '''
    bias = pd.Series(1, index=X.index, name="bias")  # Create a column of 1s
    ans = pd.concat([bias, X], axis=1)  # Concatenate the bias column to X
    return ans
    
### ANSWER CHECK
X_with_bias = add_bias(X)
X_with_bias.head()

bias   age     fare
0     1  22.0   7.2500
1     1  38.0  71.2833
2     1  26.0   7.9250
3     1  35.0  53.1000
4     1  35.0   8.0500

[Back to top](#-Index)

### Problem 2

#### A Single Node Weights

**10 Points**

The first step when defining an ANN is to assign a weight for each input of each node.  

Assuming the ANN used in this exercise uses one single node, this amounts to creating three initial weights -- one for the bias, and one weight for each feature.  

Below, use a `random.seed(42)` for reproducibility. Next, use the random normal number generator from `NumPy` to generate an array of three weights for the bias and the features.  Assign this array to the variable `weights`.
 



In [13]:
### GRADED
# Set seed for reproducibility
np.random.seed(42)

# Generate an array of three weights (bias + 2 features)
weights = np.random.normal(size=3)

### ANSWER CHECK
print(weights.shape)
print(weights)

(3,)
[ 0.49671415 -0.1382643   0.64768854]


[Back to top](#-Index)

### Problem 3

#### Computing the weighted sum

**10 Points**

Next, you are to use the weights to apply them to the features and bias. 

Below, use matrix multiplication to apply the `weights` to your data `X_with_bias` and assign the results to `weighted_sum` below.

In [15]:
### GRADED
# Compute weighted sum using matrix multiplication
weighted_sum = np.dot(X_with_bias.values, weights)

### ANSWER CHECK
weighted_sum

array([ 2.15064143, 41.41204708,  2.03477399, 30.04972499,  0.87135634])

[Back to top](#-Index)

### Problem 4

#### Sigmoid Activation

**10 Points**

After computing the weighted sum for the data you are to apply a sigmoid activation function.  Below, complete the definition of the `sigmoid` function that takes in an array of values and returns the result of applying the transformation:

$$f(x) = \frac{1}{1 + e^{-x}}$$

Finally, apply the `sigmoid` function to the array `weighted_sum` and assign the results to the variable `output`.

In [17]:
### GRADED
def sigmoid(X):
    '''
    This function applies the sigmoid transformation
    defined as 1 / (1 + e^(-x)).
    Parameters:
    X : array-like
        Input array of values.
    Returns:
    array-like
        Transformed values after applying sigmoid.
    '''
    return 1 / (1 + np.exp(-X))

output = sigmoid(weighted_sum)

### ANSWER CHECK
output

array([0.8957287 , 1.        , 0.88440005, 1.        , 0.70502785])

[Back to top](#-Index)

### Problem 5

#### Making Predictions

**10 Points**

Recall that the output of the sigmoid can be interpreted as a probability of being a member of the positive class -- survived.   Use the `output` variable to make predictions for your first pass through the neural network.  What is the accuracy of your predictions?  Assign the predictions as `preds` and accuracy as `starting_acc`. 

In [21]:
### GRADED
preds = (output > 0.5).astype(int)
starting_acc = np.mean(preds == y)

### ANSWER CHECK
print(y)
print(preds)
print(starting_acc)

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64
[1 1 1 1 1]
0.6


Great job!  Next you will examine a more complex network.